language: c
install:
  - source <(curl -SLs https://raw.githubusercontent.com/fede2cr/travis-ci-arduino/master/install.sh)
before_script:
  - arduino --install-library "ArduinoJson,IRremoteESP8266,PubSubClient,rc-switch"
  - ./travis.sh
script: build_platform esp8266
env:
  - RGB_TYPE=RGB
  - RGB_TYPE=RGBW
  - RGB_TYPE=RGBWW
  - REMOTE_TYPE=IR_REMOTE
  - REMOTE_TYPE=RF_REMOTE
  - MQTT_MODE=JSON
  - MQTT_MODE=JSON RGB_TYPE=RGBW
  - MQTT_DISCOVERY=HOME_ASSISTANT_MQTT_DISCOVERY
  - MQTT_DISCOVERY=HOME_ASSISTANT_MQTT_DISCOVERY RGB_TYPE=RGBW
matrix:
  fast_finish: true
